# Generated by Django 4.0.6 on 2022-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.TextField()),
                ('publish_date', models.CharField(max_length=50)),
                ('our_category', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('media', models.URLField()),
                ('link', models.URLField()),
                ('blog_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.TextField()),
                ('publish_date', models.CharField(max_length=50)),
                ('our_category', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('media', models.URLField()),
                ('link', models.URLField()),
                ('blog_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Refresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
