# Generated by Django 4.0.6 on 2022-10-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='profile_picture',
            field=models.ImageField(default='comments/err.png', upload_to='comments/'),
        ),
    ]
