# Generated by Django 4.0.6 on 2022-10-27 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_form_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
