# Generated by Django 4.0.6 on 2022-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_alter_form_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='profile_picture',
            field=models.ImageField(default='err.png', upload_to='comments/'),
        ),
    ]
