# Generated by Django 4.0.6 on 2022-10-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_alter_form_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Comment',
        ),
    ]
